---
abstract: 'command-line argument and option processor'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  IO::Capture::Stdout: '0'
  Module::Build::Pluggable::CPANfile: '0.05'
  POSIX: '0'
  Test2::Bundle::Extended: '0'
configure_requires:
  File::Spec: '0'
  Module::Build: '0.4004'
  Module::Build::Pluggable: '0'
  Module::Build::Pluggable::CPANfile: '0.05'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
keywords: []
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: OptArgs2
no_index:
  package:
    - OptArgs2::Arg
    - OptArgs2::Cmd
    - OptArgs2::Fallback
    - OptArgs2::Mo
    - OptArgs2::Opt
    - OptArgs2::Result
    - OptArgs2::Util
    - Getopt::Args2::Result
requires:
  Carp: '0'
  Encode: '2.24'
  Getopt::Long: '2.37'
  I18N::Langinfo: '0'
  List::Util: '0'
  Text::Abbrev: '0'
  perl: '5.01'
resources:
  bugtracker: https://github.com/mlawren/p5-OptArgs2/issues
  homepage: https://github.com/mlawren/p5-OptArgs2
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: git://github.com/mlawren/p5-OptArgs2.git
version: v0.0.10
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
